services:
  web:
    build: ./app
    restart: unless-stopped
    volumes:
      - ./app:/app
      - static_volume:/static
    environment:
      - REDIS_URL=redis://default:${REDIS_PASSWORD}@redis:6380/0
    networks:
      - backend
    security_opt:
      - no-new-privileges:true

  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - static_volume:/static:ro
    depends_on:
      - web
    networks:
      - backend
    cap_add:
      - NET_ADMIN

  redis:
    image: redis:7-bookworm
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    networks:
      - backend
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

networks:
  backend:
    driver: bridge

volumes:
  static_volume:
  redis_data: